import boolean from '../../assets/marketplace/boolean-egyptian.svg'
import road from '../../assets/marketplace/road-to-egypt.svg'
import philomena from '../../assets/marketplace/philomena.svg'
import blanc from '../../assets/marketplace/blanc.svg'
import ellipsia from '../../assets/marketplace/ellipsia.svg'
import lawmakers from '../../assets/marketplace/lawmakers.svg'
import veil from '../../assets/marketplace/veil.svg'
import alternating from '../../assets/marketplace/alternating.svg'
import rosemary from '../../assets/marketplace/rosemary.svg'
import beverly from '../../assets/marketplace/beverly.svg'
import areWe from '../../assets/home/are-we.svg'
import oloibiri from '../../assets/home/oloibiri.svg'


export default [
    {   id: 1,
        img: boolean,
        name: 'Boolean egyptian',
        artist: 'Clearamane',
        price: 21.00,
        quantity: 1,
        size: '200',
        type: 'Editorials',
        inCart: false,
        isFavorite: false,
    },
    {   id: 2,
        img: road,
        name: 'Road to egypt',
        artist: 'Clearamane',
        price: 11.00,
        quantity: 1,
        size: '200',
        type: 'Editorials',
        inCart: false,
        isFavorite: false,
    },
    {  
         id: 3,
        img: philomena,
        name: "Philomena '22",
        artist: 'Clearamane',
        price: 7.90,
        quantity: 1,
        size: '200',
        type: 'Photography',
        inCart: false,
        isFavorite: false,
    },
    {   id: 4,
        img: blanc,
        name: 'Blanc',
        artist: 'Clearamane',
        price: 11.00,
        quantity: 1,
        size: '200',
        type: 'Nature',
        inCart: false,
        isFavorite: false,
    },
    {   id: 5,
        img: ellipsia,
        name: 'Ellipsia',
        artist: 'Clearamane',
        price: 11.00,
        quantity: 1,
        size: '200',
        type: 'Photography',
        inCart: false,
        isFavorite: false,
    },
    {   id: 6,
        img: lawmakers,
        name: 'the lawmakers',
        artist: 'Clearamane',
        price: 30.00,
        quantity: 1,
        size: '200',
        type: 'The 90s',
        inCart: false,
        isFavorite: false,
    },
    {   id: 7,
        img: veil,
        name: 'Veil',
        artist: 'Clearamane',
        price: 25.50,
        quantity: 1,
        size: '200',
        type: 'Photography',
        inCart: false,
        isFavorite: false,
    },
    {   id: 8,
        img: alternating,
        name: 'Alternating',
        artist: 'Clearamane',
        price: 16.00,
        quantity: 1,
        size: '200',
        type: 'Editorials',
        inCart: false,
        isFavorite: false,
    },
    {   id: 9,
        img: rosemary,
        name: "Rosemary '22",
        artist: 'Clearamane',
        price: 10.00,
        size: '200',
        type: 'Photography',
        inCart: false,
    },
    {   id: 10,
        img: beverly,
        name: 'Beverly',
        artist: 'Clearamane',
        price: 12.00,
        quantity: 1,
        size: 200,
        type: 'Nature',
        inCart: false,
        isFavorite: false,
    },
    {
        id: 11,
        img: areWe,
        name: 'Are we there yet',
        artist: 'Clearamane',
        price: 13.60,
        quantity: 1,
        size: '200',
        type: 'Editorials',
        inCart: false,
        isFavorite: false,
    },
    {
        id: 12,
        img: oloibiri,
        name: 'Oloibiri 1997',
        artist: 'Clearamane',
        price: 14.00,
        quantity: 1,
        size: '200',
        type: 'Editorials',
        inCart: false,
        isFavorite: false,
    }
    
]